Front_End=['HTML','CSS','Javascript','React js']
print(Front_End)
Front_End.append('Angular.js')
print(Front_End)
Front_End.append('Express.js')
print(Front_End)
Front_End.insert(3,'Boot strap')
print("After Insert",Front_End)
Front_End.insert(1,'Tailwind')
print("After Insert",Front_End)
Front_End.pop(0)
print(Front_End)
Front_End.remove('CSS')
print(Front_End)
print(Front_End.index('Boot strap'))
print(Front_End.index('Tailwind'))