a=int(input("enter the integer value :"))
print("Before convertion",a)
print("integer value after convertion",str(a))
print("integer value after convertion",float(a))
print("integer value after convertion",complex(a))
b=float(input("enter the float value : "))
print("Before convertion",b)
print("float value after convertion",str(b))
print("float value after convertion",int(b))
print("float value after convertion",complex(b))
c=input("enter the string value :")
print("Before convertion",c)
print("string value after convertion",int(c))
print("string value after convertion",float(c))
print("string value after convertion",list(c))
print("string value after convertion",tuple(c))