Num='javascript','NoSQL','HTML','CSS','java','cython','python','Angularjs','Reactjs','ironpython','rubypython','pypy','Zython','SQL','Mangodb'
print(Num)
print(type(Num))
#Tuple uncpacking
#acessing using indexing
print("Acessing list elements using +ve indexing")
print(Num[0])
print(Num[1])
print(Num[2])
print(Num[3])
print(Num[4])
print(Num[5])
print(Num[6])
print(Num[7])
print(Num[8])
print(Num[9])
print(Num[10])
print(Num[11])
print(Num[12])
print(Num[14])
#acessing using negative indexing
print("Acessing using -ve indexing")
print(Num[-15])
print(Num[-14])
print(Num[-13])
print(Num[-12])
print(Num[-11])
print(Num[-10])
print(Num[-9])
print(Num[-8])
print(Num[-7])
print(Num[-6])
print(Num[-5])
print(Num[-4])
print(Num[-3])
print(Num[-2])
print(Num[-1])